#!/bin/sh
echo $0
echo `dirname $0`
APPLICATION_DIR=`dirname "$0"`
cd "$APPLICATION_DIR/../Java"
java -Xdock:name="NyquistIDE" -Xdock:icon=`dirname $0`/../Resources/Nyquist.icns -Dcom.apple.mrj.application.apple.menu.about.name=NyquistIDE -Dapple.laf.useScreenMenuBar=true -DisOSXbundle=true -jar jnyqide.jar 
